src/Entity/UserProfile.php
<?php

namespace App\Entity;

use App\Repository\UserProfileRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: UserProfileRepository::class)]
class UserProfile
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $name = null;

    #[ORM\Column(length: 1024, nullable: true)]
    private ?string $bio = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $website_url = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $x_username = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $company = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $location = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $date_of_birth = null;

    #[ORM\OneToOne(inversedBy: 'userProfile', cascade: ['persist', 'remove'])]
    #[ORM\JoinColumn(nullable: false)]
    private ?User $user = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $image = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(?string $name): static
    {
        $this->name = $name;

        return $this;
    }

    public function getBio(): ?string
    {
        return $this->bio;
    }

    public function setBio(?string $bio): static
    {
        $this->bio = $bio;

        return $this;
    }

    public function getWebsiteUrl(): ?string
    {
        return $this->website_url;
    }

    public function setWebsiteUrl(?string $website_url): static
    {
        $this->website_url = $website_url;

        return $this;
    }

    public function getXUsername(): ?string
    {
        return $this->x_username;
    }

    public function setXUsername(?string $x_username): static
    {
        $this->x_username = $x_username;

        return $this;
    }

    public function getCompany(): ?string
    {
        return $this->company;
    }

    public function setCompany(?string $company): static
    {
        $this->company = $company;

        return $this;
    }

    public function getLocation(): ?string
    {
        return $this->location;
    }

    public function setLocation(?string $location): static
    {
        $this->location = $location;

        return $this;
    }

    public function getDateOfBirth(): ?\DateTimeInterface
    {
        return $this->date_of_birth;
    }

    public function setDateOfBirth(\DateTimeInterface $date_of_birth): static
    {
        $this->date_of_birth = $date_of_birth;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(User $user): static
    {
        $this->user = $user;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(?string $image): static
    {
        $this->image = $image;

        return $this;
    }
}

src/Controller/ProfileController.php
<?php

namespace App\Controller;

use App\Entity\User;
use App\Repository\MicroPostRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class ProfileController extends AbstractController
{
    #[Route('/profile/{id}', name: 'app_profile')]
    public function show(User $user, MicroPostRepository $posts): Response
    {
        return $this->render('profile/show.html.twig', [
            'user' => $user,
            'posts' => $posts->findAllByAuthor($user),
        ]);
    }

    #[Route('/profile/{id}/follows', name: 'app_profile_follows')]
    public function follows(User $user): Response
    {
        return $this->render('profile/follows.html.twig', [
            'user' => $user,
        ]);
    }

    #[Route('/profile/{id}/followers', name: 'app_profile_followers')]
    public function followers(User $user): Response
    {
        return $this->render('profile/followers.html.twig', [
            'user' => $user,
        ]);
    }
}

templates/profile/_profile_header.html.twig
<div class="flex items-center">
    <div>
        <div class="mb-2">
            {{ include('shared/_avatar.html.twig', { profile: user.userProfile, size: 32 }) }}
        </div>
        <div class="text-2xl">{{ user.userProfile.name ?? user.email }}</div>
        <div class="text-lg text-gray-500 dark:text-gray-400 font-normal">{{ user.email }}</div>

        {% if user.userProfile != null %}
            <div class="text-base text-gray-800 dark:text-gray-400 font-normal">
                {{ user.userProfile.bio ?? 'No bio' }}
            </div>

            <div class="flex">
                <div class="text-base text-gray-500 dark:text-gray-400 font-normal">
                    <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5 inline" viewBox="0 0 20 20" fill="currentColor">
                        <path fill-rule="evenodd" d="M5.05 4.05a7 7 0 119.9 9.9L10 18.9l-4.95-4.95a7 7 0 010-9.9zM10 11a2 2 0 100-4 2 2 0 000 4z" clip-rule="evenodd" />
                    </svg> {{ user.userProfile.location ?? 'Unknown' }}
                </div>
                <div class="text-base text-gray-500 dark:text-gray-400 font-normal ml-4">
                    <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5 inline" viewBox="0 0 20 20" fill="currentColor">
                        <path fill-rule="evenodd" d="M6 3a1 1 0 011-1h.01a1 1 0 010 2H7a1 1 0 01-1-1zm2 3a1 1 0 00-2 0v1a2 2 0 00-2 2v1a2 2 0 00-2 2v.683a3.7 3.7 0 011.055.485 1.704 1.704 0 001.89 0 3.704 3.704 0 014.11 0 1.704 1.704 0 001.89 0 3.704 3.704 0 014.11 0 1.704 1.704 0 001.89 0A3.7 3.7 0 0118 12.683V12a2 2 0 00-2-2V9a2 2 0 00-2-2V6a1 1 0 10-2 0v1h-1V6a1 1 0 10-2 0v1H8V6zm10 8.868a3.704 3.704 0 01-4.055-.036 1.704 1.704 0 00-1.89 0 3.704 3.704 0 01-4.11 0 1.704 1.704 0 00-1.89 0A3.704 3.704 0 012 14.868V17a1 1 0 001 1h14a1 1 0 001-1v-2.132zM9 3a1 1 0 011-1h.01a1 1 0 110 2H10a1 1 0 01-1-1zm3 0a1 1 0 011-1h.01a1 1 0 110 2H13a1 1 0 01-1-1z" clip-rule="evenodd" />
                    </svg> {% if user.userProfile.dateOfBirth %}{{ user.userProfile.dateOfBirth | date("M j, Y") }}{% else %}Unknown{% endif %}
                </div>
            </div>
        {% endif %}
    </div>
    <div class="ml-16 text-2xl">
        {{ include('follower/_follow_button.html.twig', { userToFollow: user }) }}
    </div>
</div>

templates/profile/_profile_tabs.html.twig
{% embed 'shared/_tabs.html.twig' %}
    {% block tabs %}
        {% embed 'shared/_tab.html.twig' with { route: 'app_profile' } %}
            {% block content %}
                Posts <span class="px-2 rounded-md bg-gray-200 dark:bg-gray-700">{{ user.posts.count }}</span>
            {% endblock %}
            {% block path %}
                {{ path('app_profile', { id: user.id }) }}
            {% endblock %}
        {% endembed %}

        {% embed 'shared/_tab.html.twig' with { route: 'app_profile_follows', classes: 'ml-2' } %}
            {% block content %}
                Follows <span class="px-2 rounded-md bg-gray-200 dark:bg-gray-700">{{ user.follows.count }}</span>
            {% endblock %}
            {% block path %}
                {{ path('app_profile_follows', { id: user.id }) }}
            {% endblock %}
        {% endembed %}

        {% embed 'shared/_tab.html.twig' with { route: 'app_profile_followers', classes: 'ml-2' } %}
            {% block content %}
                Followers <span class="px-2 rounded-md bg-gray-200 dark:bg-gray-700">{{ user.followers.count }}</span>
            {% endblock %}
            {% block path %}
                {{ path('app_profile_followers', { id: user.id }) }}
            {% endblock %}
        {% endembed %}
    {% endblock %}
{% endembed %}

templates/profile/followers.html.twig
{% extends 'base.html.twig' %}

{% block title %}User Profile → Followers{% endblock %}

{% block bread %}
    → User Profile → <a href="{{ path('app_profile', {id: user.id}) }}">{{ user.userProfile.name }}</a> → Followers
{% endblock %}

{% block body %}
    {{ include ('profile/_profile_header.html.twig') }}
    {{ include ('profile/_profile_tabs.html.twig') }}
    {{ include ('follower/_follower_list.html.twig', { users: user.followers }) }}
{% endblock %}

templates/profile/follows.html.twig
{% extends 'base.html.twig' %}

{% block title %}User Profile → Follows{% endblock %}

{% block bread %}
    → User Profile → <a href="{{ path('app_profile', {id: user.id}) }}">{{ user.userProfile.name }}</a> → Follows
{% endblock %}

{% block body %}
    {{ include ('profile/_profile_header.html.twig') }}
    {{ include ('profile/_profile_tabs.html.twig') }}
    {{ include ('follower/_follower_list.html.twig', { users: user.follows }) }}
{% endblock %}

templates/profile/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ user.userProfile.name }}{% endblock %}

{% block bread %}
    → User Profile → {{ user.userProfile.name }}
{% endblock %}

{% block body %}
    {{ include ('profile/_profile_header.html.twig') }}
    {{ include ('profile/_profile_tabs.html.twig') }}
    
    {{ include ('micro_post/_post_list.html.twig', { posts: posts }) }}
{% endblock %}